version: '3'

services:

  node:
    build:
      context: .
      dockerfile: Node.Dockerfile
    env_file:
      - .env
    volumes:
      - ./app:/usr/src/app
    ports:
      - 8080:8080
    image: jwthomas/album-reviews-node:latest
