version: '3'

services:
  sql:
    image: mysql:latest
    env_file:
      - .env
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - 3306:3306
  node:
    build:
      context: .
      dockerfile: Node.Dockerfile
    env_file:
      - .env
    volumes:
      - ./app:/usr/src/app
    ports:
      - 8080:8080

volumes:
  mysqldata: {}